name: Frontend CI 

on:
  pull_request:
    branches: [ "main" ]   
    paths-ignore:          
      - 'src/data/**'
      - 'src/types/**'
      - 'src/styles/**'
      - 'src/hooks/**'
      - 'src/lib/**'
      - 'src/components/ui/**'
      - 'src/pages/NotFound.tsx'
      - 'src/vite-env.d.ts'
      - 'src/index.css'
      - 'src/App.css'
      - 'src/fonts.css'
      - 'src/**/*.test.*'
      - 'src/**/*.spec.*'
      - 'src/**/*.mock.*'
      - 'src/**/__mocks__/**'
      - 'src/**/__tests__/**'
      - 'public/**'
      - '*.md'
      - '*.yml'
      - '*.yaml'
      - '*.lock'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: |
          if [ "$(npm pkg get scripts.lint)" != "undefined" ]; then
            npm run lint
          else
            echo "No lint script found, skipping..."
          fi

      - name: Run tests
        run: |
          if [ "$(npm pkg get scripts.test)" != "undefined" ]; then
            npm test
          else
            echo "No test script found, skipping..."
          fi

      - name: Build project
        run: |
          if [ "$(npm pkg get scripts.build)" != "undefined" ]; then
            npm run build
          else
            echo "No build script found, skipping..."
          fi

      - name: Check links
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --verbose --no-progress .
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
