name: Frontend CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: |
          if npm run | grep -q "lint"; then
            npm run lint
          else
            echo "No lint script found, skipping..."
          fi

      - name: Run tests
        run: |
          if npm run | grep -q "test"; then
            npm test
          else
            echo "No test script found, skipping..."
          fi

      - name: Build project
        run: |
          if npm run | grep -q "build"; then
            npm run build
          else
            echo "No build script found, skipping..."
          fi

      - name: Check links
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --verbose --no-progress .
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
